### ISSUE TITLE
Josemi deja de crear cuentas y arreglemos esto

### ISSUE THREAD

**Issue by daviiid99** [itatsu0/ultra-java-archive-examples#1]
Deja de huir de mi, soy una persona que se equivocó, no un monstruo

De verdad te hace feliz que alguien sufra por errores que no quiso cometer?

Creía que si me equivocaba alguna vez por algo valorarías mas las veces que he hecho algo bueno por ti y nos mis errores

**Comment by daviiid99** [comment]
Esto no tiene que acabar tan mal, yo solo soy una persona que se ha equivocado

Cuantas veces debo pedirte perdón por no haber cumplido mi promesa :(

No es castigo suficiente lo que ya he sufrido para querer seguir prolongándolo

**Comment by daviiid99** [comment]
Si no cumplí mi promesa de no hablarte no era porque quería que estuvieras mal y no quisiera respetarte como me dijiste por telegram

Sino porque estaba preocupado, quería ayudarte de alguna forma y no sabia como

**Comment by daviiid99** [comment]
Sabes lo sensible que soy, aguanté 10 días sin hablarte pero estaba tan preocupado que no pude evitarlo y te hablé

Y lo siento, siento haberlo hecho, pero yo no lo hice por hacerte daño

**Comment by daviiid99** [comment]
Yo quería haber cumplido la promesa que te hice y no hablarte el tiempo que necesitaras para que estuvieras bien

Pero yo no tengo a nadie mas que a ti y no podía evitar pensar en ti y me preocupaba en exceso y te hablé

Solo fue eso, es la verdad

**Comment by daviiid99** [comment]
Yo no he sido nunca malo contigo, por favor, ten piedad conmigo, no me hagas daño más tiempo :(

Si me equivoqué queriendo hacerte un libro, lo siento, yo solo quería animarte y no sabia como

**Comment by itatsu0** [comment]
disculpe, creo que se ha confundido

**Comment by daviiid99** [comment]
Siempre he hecho todo lo que he podido por hacerte feliz.
Te lo he dado siempre todo solo por alegrarte algo

Nunca he pensado en hacerte mal, si te hice daño nunca fue queriendo, yo nunca te haría daño

Soy incapaz de enfadarme contigo o tratarte mal, solo se llorar

**Comment by daviiid99** [comment]
> disculpe, creo que se ha confundido

Sabes que no me he confundido, tenias hasta hace nada la foto de chili de perfil

**Comment by itatsu0** [comment]
> 
> 
> > disculpe, creo que se ha confundido
> 
> Sabes que no me he confundido, tenias hasta hace nada la foto de chili de perfil

no se quien es chili, antes de la del f9, tenia un doggo de google jsjs, pero a mi profesor no queria. Siento mucho sus problemas personales, pero creo que es mejor borre sus mensajes, a ver si los van a ver alguien, gracias! 😅😅
